import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PowerSyncProvider } from "@/lib/powersync/PowersyncProvider";
import ConnectionStatus from "@/components/ConnectionStatus";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PowerSyncProvider>
          <div>
            <ConnectionStatus />
            {children}
          </div>
        </PowerSyncProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
