import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PowerSyncProvider } from "@/lib/powersync/PowersyncProvider";
import ConnectionStatus from "@/components/ConnectionStatus";
import { Toaster } from "react-hot-toast";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shadcn-sidebar/app-sidebar";
import Header from "@/components/main-components/navigation/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />

          <SidebarInset>
            <PowerSyncProvider>
              <div>

                <Header />
                <ConnectionStatus />
                {children}
              </div>

            </PowerSyncProvider>
            <Toaster position="top-right" />
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
